

import AddToCartHeaderCall from '@/app/components/cliants/AddToCartHeaderCall'
import ShowProductsCall from '@/app/components/cliants/ShowProductsCall'
import React from 'react'

export const metadata = {
    title: 'Products page',
    description: 'Generated by create next app',
}

const Products = () => {
    return (
        <>
            <div className="flex flex-col gap-x-5 gap-y-10 justify-evenly flex-wrap">
                <div className="flex flex-col gap-y-10">
                    <AddToCartHeaderCall></AddToCartHeaderCall>
                </div>

                <div className="flex flex-col gap-y-10">
                    <ShowProductsCall></ShowProductsCall>
                </div>
            </div>
        </>
    )
}

export default Products