import ApiNavbar from '@/app/components/cliants/ApiNavbar';
import ProductsCardAdmin from '@/app/componentsAdmin/ProductsCardAdmin';
import dbConnect from '@/utils/database';
import { PtModels2 } from '@/utils/models/allModel';

import React from 'react'

export const metadata = {
    title: 'Admin page',
    description: 'Generated by create next app',
}

const Admin = async () => {

    await dbConnect();

    const sortAllProductsList = await PtModels2.find();
    const sortAllProductsArray = [...sortAllProductsList];

  

    // const productsJSONObjectFS = await getAllProductsData();
    // const productsArrayFS = productsJSONObjectFS.products;
    // console.log(productsArrayFS);


    return (
        <>
            <div className="px-5 2xl:container text-2xl">
                <div className="flex flex-col gap-y-10">
                    <div className="">
                        This is Admin page...
                    </div>

                    <ApiNavbar></ApiNavbar>

                    <div className='flex flex-wrap gap-x-10 gap-y-10 justify-evenly pb-10'>

                        {sortAllProductsArray.map((curItem, index) => {
                            return (
                                <>
                                    <ProductsCardAdmin key={index}
                                        id={curItem.id}
                                        img={curItem.img}
                                        title={curItem.title}
                                        description={curItem.description}
                                        price={curItem.price}
                                    >
                                    </ProductsCardAdmin>
                                </>
                            )
                        })}
                    </div>

                    {/* <div className='flex flex-wrap gap-x-10 gap-y-10 justify-evenly pb-10'>
                        {productsArrayFS.map((curItem, index) => {
                            return (
                                <ProductsCardAdmin key={curItem.id}
                                    {...curItem}>
                                </ProductsCardAdmin>
                            )
                        })}
                    </div> */}
                </div>
            </div>

        </>
    )
}

export default Admin