import ProductsDisplayAdmin from '@/app/componentsAdmin/ProductsDisplayAdmin';
import axios from 'axios';

import React from 'react'

export const metadata = {
    title: 'Admin page',
    description: 'Generated by create next app',
}

export const revalidate = 1;
// Data will be fetch from locagost:3000/api/product/read at every 01 sec....


const Admin = async () => {

    return (
        <>
            <div className="px-5 2xl:container text-2xl">
                <div className="flex flex-col gap-y-5 -mt-5">
                    <ProductsDisplayAdmin isAdmin={true}></ProductsDisplayAdmin>
                </div>
            </div>

        </>
    )
}

export default Admin