import React from 'react'

export const metadata = {
    title: 'About page',
    description: 'Generated by create next app',
}

const about = () => {
    return (
        <>
            <div className="">
                This is About page...
            </div>
        </>
    )
}

export default about