import React from 'react'

export const metadata = {
  title: 'Contact page',
  description: 'Generated by create next app',
}

const contact = () => {
  return (
    <div className='px-5'>This is Contact page...</div>
  )
}

export default contact