


import Header from './components/servers/header'
import dbConnect from '@/utils/database';
import { PtModels2 } from '@/utils/models/allModel';
import ProductsCardAdmin from './componentsAdmin/ProductsCardAdmin';
import ApiNavbar from './components/cliants/ApiNavbar';


export const metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}


export default async function Home() {

  await dbConnect();

  // console.log("Now , Lets's Add data in Database");

  const sortAllProductsList = await PtModels2.find().sort({ "id": 1 });
  const sortAllProductsArray = [...sortAllProductsList];

  return (
    <>

      <div className="flex flex-col gap-y-10 pb-20">

        <div className="w-full bg-antiquewhite rounded-b-full px-20 py-2">
          <Header></Header>
        </div>
        <main className="px-5">


          <ApiNavbar></ApiNavbar>

 

          <div className='flex flex-wrap gap-x-10 gap-y-10 justify-evenly pb-10 mt-10'>


            {sortAllProductsArray.map((curItem, index) => {
              return (
                <>
                  <ProductsCardAdmin key={index}
                    id={curItem.id}
                    img={curItem.img}
                    title={curItem.title}
                    description={curItem.description}
                    price={curItem.price}
                  >
                  </ProductsCardAdmin>
                </>
              )
            })}
          </div>

        </main>
      </div>
    </>
  )
}
